#################### STAGING ####################
deploy-stage:
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass
    - sshpass -V
    - export SSHPASS=$USER_PASS_STAGE
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ls -al && pwd
  script:
    - sshpass -e ssh $USER_NAME_STAGE@$HOST_NAME_STAGE "cd ~/project/its-photocontest/backend && git checkout dev && git pull && docker-compose down && docker-compose -f docker-compose-stage.yml up -d"
  environment:
    name: staging
  only:
    - dev

#################### PRODUCTION ####################
deploy-prod:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY_PROD" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh $USER_NAME_PROD@$HOST_NAME_PROD "cd ~/apps/ITS_PhotoContest-Backend && git checkout master && git pull && pm2 restart photo-api"
  environment:
    name: production
  only:
    - master
  # - tags