version: "3"

services:
  ######### API #########
  api-server:
    container_name: api-server
    build: .
    # depends_on:
    #   - elasticsearch
    #   - redis
    #   - rabbitmq
    env_file:
      - .env
    command: npm run prod-aws
    ports:
      - "${PORT}:${PORT}"
      - "${PGPORT}:${PGPORT}"
    networks:
      - default

  ######### REDIS #########
  # redis:
  #   container_name: redis
  #   image: redis:5.0.3-alpine3.9
  #   hostname: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis-data:/data
  #   entrypoint: redis-server --appendonly yes
  #   restart: always
  #   networks:
  #     - default

  ######### ELASTIC SEARCH #########
  # elasticsearch:
  #   container_name: elasticsearch
  #   image: elasticsearch:6.6.1
  #   hostname: elasticsearch
  #   environment:
  #     - cluster.name=photocontest
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms300m -Xmx300m
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   volumes:
  #     - es-data:/usr/share/elasticsearch/data
  #   networks:
  #     - default

  ######### RABBIT MQ #########
  # rabbitmq:
  #   container_name: rabbitmq
  #   image: rabbitmq:3.7-management-alpine
  #   hostname: rabbitmq
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=supersecretpassword
  #   ports:
  #     - 15672:15672
  #     - 5672:5672
  #   networks:
  #     - default

# volumes:
#   es-data:
#     driver: local
#   redis-data:

networks:
  default:
    driver: bridge
