version: "3"

services:
  api.photocontest.marcostevanon.ovh:
    container_name: api.photocontest.marcostevanon.ovh
    image: registry.gitlab.com/its-photocontest/backend:dev
    restart: always
    labels:
      - "traefik.frontend.rule=Host:api.photocontest.marcostevanon.ovh"
      - "traefik.port=5671"
      - "traefik.enable=true"
    env_file:
      - .env
    command: npm run prod-vultr
    networks:
      - traefik

networks:
  traefik:
    external: true