version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.6.1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - backend

  redis:
    container_name: redis
    image: redis:5.0.3-alpine3.9
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
    entrypoint: redis-server --appendonly yes
    networks: 
      - backend

  api:
    container_name: photocontest_api
    build: .
    depends_on: 
      - elasticsearch
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=stage
    env_file: .env
    ports:
      - 5671:5671
    command: ["node", "index.js"]
    networks: 
      - backend

volumes:
  esdata1:
    driver: local
  redis-data:

networks: 
  backend: